/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.23
 * Generated at: 2012-01-05 07:31:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/jsp/common/header.jsp", out, false);
      out.write("\r\n");
      out.write("<div class=\"inner\">\r\n");
      out.write("    <div id=\"content\">\r\n");
      out.write("        <div class=\"box featured-box\">\r\n");
      out.write("            <div class=\"box-content\">\r\n");
      out.write("                <ul id=\"myRoundabout\">\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <div class=\"prod_holder\">\r\n");
      out.write("                            <a href=\"register_new_return.jsp\">\r\n");
      out.write("                                <img src=\"image/register.png\" alt=\"Spicylicious store\" />\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <div class=\"prod_holder\">\r\n");
      out.write("                            <a href=\"product.html\">\r\n");
      out.write("                                <img src=\"image/snow-clad-himalayas-wallpapers.jpg\" alt=\"Spicylicious store\" />\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <h3>The Himalayas</h3>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <div class=\"prod_holder\">\r\n");
      out.write("                            <a href=\"product.html\">\r\n");
      out.write("                                <img src=\"image/lake_manas_sarovar.jpg\" alt=\"Spicylicious store\" />\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <h3>Manasa Sarovar</h3>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <div class=\"prod_holder\">\r\n");
      out.write("                            <a href=\"product.html\">\r\n");
      out.write("                                <img src=\"image/kailash_lingam.jpg\" alt=\"Spicylicious store\" />\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <h3>Kailasha Lingam</h3>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <a href=\"#\" class=\"previous_round\">Previous</a>\r\n");
      out.write("                <a href=\"#\" class=\"next_round\">Next</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"box\">\r\n");
      out.write("            <h2 class=\"heading-title\">\r\n");
      out.write("                <span>Welcome to Ati Rudra Parayanam - 2012</span>\r\n");
      out.write("            </h2>\r\n");
      out.write("            <div class=\"box-content\">\r\n");
      out.write("                <p>By the Divine Lord's Loving Grace we are being blessed with an oppurtunity to conduct the Ati\r\n");
      out.write("                    Rudra Parayanam for the year 2012 on the Himalayas facing Mount Kailash. Please register for further\r\n");
      out.write("                    updates.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/jsp/common/footer.jsp", out, false);
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\tvar interval = 0;\r\n");
      out.write("\t\t$('ul#myRoundabout').roundabout({\r\n");
      out.write("\t\t\t'btnNext' : '.next_round',\r\n");
      out.write("\t\t\t'btnPrev' : '.previous_round'\r\n");
      out.write("\t\t}).hover(function() {\r\n");
      out.write("\t\t\tclearInterval(interval);\r\n");
      out.write("\t\t}, function() {\r\n");
      out.write("\t\t\tinterval = startAutoPlay();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\tinterval = startAutoPlay();\r\n");
      out.write("\t});\r\n");
      out.write("\tfunction startAutoPlay() {\r\n");
      out.write("\t\treturn setInterval(function() {\r\n");
      out.write("\t\t\t$('ul#myRoundabout').roundabout_animateToPreviousChild();\r\n");
      out.write("\t\t}, 3000);\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
