/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.23
 * Generated at: 2012-01-05 13:24:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<title>Ati Rudra Parayanam - 2012</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"stylesheet/stylesheet.css\" type=\"text/css\" media=\"screen\" />\r\n");
      out.write("<link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css' />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"stylesheet/jquery-ui-1.8.9.custom.css\" />\r\n");
      out.write("<!-- jQuery and Custom scripts -->\r\n");
      out.write("<script src=\"js/jquery-1.5.2.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"js/jquery.cycle.lite.1.0.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"js/custom_scripts.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"js/jquery.roundabout.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery-ui-1.8.9.custom.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/tabs.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.form.js\"></script>\r\n");
      out.write("<!-- Tipsy -->\r\n");
      out.write("<script src=\"js/tipsy/jquery.tipsy.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<link href=\"js/tipsy/css.tipsy.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- MAIN WRAPPER -->\r\n");
      out.write("    <div id=\"container\">\r\n");
      out.write("        <!-- HEADER -->\r\n");
      out.write("        <div id=\"header\">\r\n");
      out.write("            <div class=\"inner\">\r\n");
      out.write("                <div id=\"logo\">\r\n");
      out.write("                    <a href=\"index.html\">\r\n");
      out.write("                        <img src=\"image/logo.png\" width=\"217\" height=\"141\" alt=\"Spicylicious store\" />\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"welcome\">\r\n");
      out.write("                    Namaste! Please\r\n");
      out.write("                    <a href=\"#\">login</a>\r\n");
      out.write("                    or\r\n");
      out.write("                    <a href=\"#\">create an account</a>\r\n");
      out.write("                    .\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"menu\">\r\n");
      out.write("                    <ul id=\"topnav\">\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"index.html\">Home</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"category.html\" title=\"Ati Rudra Parayanam at Kailash for 2012\">2012 - Kailash\r\n");
      out.write("                                Yatra</a>\r\n");
      out.write("                            <ul class=\"children\">\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"register_new_return.jsp\">\r\n");
      out.write("                                        Register\r\n");
      out.write("                                        <span style=\"font-size: smaller; font-style: italic;\">(Closes Jan/30/12)</span>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"category.html\">Itinerary</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"category.html\">FAQ</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"category.html\">Satsang</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"category.html\">Videos</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"category.html\">Photos</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"category.html\">Namakam</a>\r\n");
      out.write("                            <ul class=\"children\">\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"category.html\">Anuvakam 1</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"category.html\">Anuvakam 2</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"category.html\">Anuvakam 3</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"category.html\">Anuvakam 4</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"category.html\">Anuvakam 5</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"category.html\">Anuvakam 6</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"category.html\">Anuvakam 7</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"category.html\">Anuvakam 8</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"category.html\">Anuvakam 9</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"category.html\">Anuvakam 10</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"category.html\">Anuvakam 11</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"category.html\">Chamakam</a>\r\n");
      out.write("                            <ul class=\"children\">\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"category.html\">Anuvakam 1</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"category.html\">Anuvakam 2</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"category.html\">Anuvakam 3</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"category.html\">Anuvakam 4</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"category.html\">Anuvakam 5</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"category.html\">Anuvakam 6</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"category.html\">Anuvakam 7</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"category.html\">Anuvakam 8</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"category.html\">Anuvakam 9</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"category.html\">Anuvakam 10</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"category.html\">Anuvakam 11</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"category.html\">Past Parayanams</a>\r\n");
      out.write("                            <ul class=\"children\">\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"category.html\">2011</a>\r\n");
      out.write("                                    <ul class=\"children2\">\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <a href=\"category.html\">Satsang</a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <a href=\"category.html\">Videos</a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <a href=\"category.html\">Photos</a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"category.html\">2010</a>\r\n");
      out.write("                                    <ul class=\"children2\">\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <a href=\"category.html\">Satsang</a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <a href=\"category.html\">Videos</a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <a href=\"category.html\">Photos</a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"category.html\">Background</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- END OF HEADER -->\r\n");
      out.write("        <!-- CONTENT -->\r\n");
      out.write("        <div id=\"content_holder\" class=\"fixed\">");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
